# Generated by Django 5.0.3 on 2024-04-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_customer_order_customer_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.99, max_digits=100),
        ),
    ]
