# Generated by Django 5.0.3 on 2024-04-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_customer_discount_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['price_with_discount'], name='price_with_discount_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='price_index'),
        ),
    ]
