# Generated by Django 5.0.3 on 2024-04-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_order_price_with_discount_index_product_price_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='amount greater than 0'),
        ),
    ]
